# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 578)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 821, 571))
        self.tabWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(86, 164, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_3.setObjectName("label_3")
        self.table_features = QtWidgets.QTableWidget(self.tab_5)
        self.table_features.setGeometry(QtCore.QRect(20, 50, 391, 411))
        self.table_features.setObjectName("table_features")
        self.table_features.setColumnCount(0)
        self.table_features.setRowCount(0)
        self.btn_features_apply = QtWidgets.QPushButton(self.tab_5)
        self.btn_features_apply.setGeometry(QtCore.QRect(640, 490, 121, 31))
        self.btn_features_apply.setStyleSheet("")
        self.btn_features_apply.setObjectName("btn_features_apply")
        self.lbl_features_count = QtWidgets.QLabel(self.tab_5)
        self.lbl_features_count.setGeometry(QtCore.QRect(150, 500, 61, 16))
        self.lbl_features_count.setObjectName("lbl_features_count")
        self.label_51 = QtWidgets.QLabel(self.tab_5)
        self.label_51.setGeometry(QtCore.QRect(20, 500, 121, 16))
        self.label_51.setObjectName("label_51")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(430, 20, 71, 16))
        self.label_9.setObjectName("label_9")
        self.table_features_y = QtWidgets.QTableWidget(self.tab_5)
        self.table_features_y.setGeometry(QtCore.QRect(430, 50, 101, 411))
        self.table_features_y.setObjectName("table_features_y")
        self.table_features_y.setColumnCount(0)
        self.table_features_y.setRowCount(0)
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(550, 20, 71, 16))
        self.label_10.setObjectName("label_10")
        self.table_features_labels = QtWidgets.QTableWidget(self.tab_5)
        self.table_features_labels.setGeometry(QtCore.QRect(550, 50, 191, 411))
        self.table_features_labels.setObjectName("table_features_labels")
        self.table_features_labels.setColumnCount(0)
        self.table_features_labels.setRowCount(0)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_52 = QtWidgets.QLabel(self.tab)
        self.label_52.setGeometry(QtCore.QRect(30, 500, 121, 16))
        self.label_52.setObjectName("label_52")
        self.lbl_features_count_2 = QtWidgets.QLabel(self.tab)
        self.lbl_features_count_2.setGeometry(QtCore.QRect(160, 500, 61, 16))
        self.lbl_features_count_2.setObjectName("lbl_features_count_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.label_4.setObjectName("label_4")
        self.table_features_2 = QtWidgets.QTableWidget(self.tab)
        self.table_features_2.setGeometry(QtCore.QRect(30, 50, 391, 411))
        self.table_features_2.setObjectName("table_features_2")
        self.table_features_2.setColumnCount(0)
        self.table_features_2.setRowCount(0)
        self.btn_features_apply_2 = QtWidgets.QPushButton(self.tab)
        self.btn_features_apply_2.setGeometry(QtCore.QRect(650, 490, 121, 31))
        self.btn_features_apply_2.setStyleSheet("")
        self.btn_features_apply_2.setObjectName("btn_features_apply_2")
        self.table_features_labels_2 = QtWidgets.QTableWidget(self.tab)
        self.table_features_labels_2.setGeometry(QtCore.QRect(560, 50, 191, 411))
        self.table_features_labels_2.setObjectName("table_features_labels_2")
        self.table_features_labels_2.setColumnCount(0)
        self.table_features_labels_2.setRowCount(0)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(440, 20, 71, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(560, 20, 71, 16))
        self.label_12.setObjectName("label_12")
        self.table_features_y_2 = QtWidgets.QTableWidget(self.tab)
        self.table_features_y_2.setGeometry(QtCore.QRect(440, 50, 101, 411))
        self.table_features_y_2.setObjectName("table_features_y_2")
        self.table_features_y_2.setColumnCount(0)
        self.table_features_y_2.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "gabor "))
        self.btn_features_apply.setText(_translate("MainWindow", " GABOR U Y G U L A"))
        self.lbl_features_count.setText(_translate("MainWindow", "0"))
        self.label_51.setText(_translate("MainWindow", "Tamlanan resim sayısı :"))
        self.label_9.setText(_translate("MainWindow", "y  L i s t"))
        self.label_10.setText(_translate("MainWindow", "L a b e l s"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "GABOR"))
        self.label_52.setText(_translate("MainWindow", "Tamlanan resim sayısı :"))
        self.lbl_features_count_2.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "GLCM"))
        self.btn_features_apply_2.setText(_translate("MainWindow", "GLCM U Y G U L A"))
        self.label_11.setText(_translate("MainWindow", "y  L i s t"))
        self.label_12.setText(_translate("MainWindow", "L a b e l s"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "GLCM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

